/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicClinicIdRouteImport } from './routes/clinic.$clinicId'
import { Route as ApiPublicClinicsRouteImport } from './routes/api/public/clinics'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicClinicsClinicIdRouteImport } from './routes/api/public/clinics.$clinicId'
import { Route as ApiPublicClinicClinicIdRouteImport } from './routes/api/public/clinic.$clinicId'

const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicClinicIdRoute = ClinicClinicIdRouteImport.update({
  id: '/clinic/$clinicId',
  path: '/clinic/$clinicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClinicsRoute = ApiPublicClinicsRouteImport.update({
  id: '/api/public/clinics',
  path: '/api/public/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClinicsClinicIdRoute =
  ApiPublicClinicsClinicIdRouteImport.update({
    id: '/$clinicId',
    path: '/$clinicId',
    getParentRoute: () => ApiPublicClinicsRoute,
  } as any)
const ApiPublicClinicClinicIdRoute = ApiPublicClinicClinicIdRouteImport.update({
  id: '/api/public/clinic/$clinicId',
  path: '/api/public/clinic/$clinicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/promotions': typeof PromotionsRoute
  '/clinic/$clinicId': typeof ClinicClinicIdRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/clinics': typeof ApiPublicClinicsRouteWithChildren
  '/api/public/clinic/$clinicId': typeof ApiPublicClinicClinicIdRoute
  '/api/public/clinics/$clinicId': typeof ApiPublicClinicsClinicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/promotions': typeof PromotionsRoute
  '/clinic/$clinicId': typeof ClinicClinicIdRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/clinics': typeof ApiPublicClinicsRouteWithChildren
  '/api/public/clinic/$clinicId': typeof ApiPublicClinicClinicIdRoute
  '/api/public/clinics/$clinicId': typeof ApiPublicClinicsClinicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/promotions': typeof PromotionsRoute
  '/clinic/$clinicId': typeof ClinicClinicIdRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/clinics': typeof ApiPublicClinicsRouteWithChildren
  '/api/public/clinic/$clinicId': typeof ApiPublicClinicClinicIdRoute
  '/api/public/clinics/$clinicId': typeof ApiPublicClinicsClinicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/categories'
    | '/compare'
    | '/dashboard'
    | '/promotions'
    | '/clinic/$clinicId'
    | '/api/public/bookings'
    | '/api/public/clinics'
    | '/api/public/clinic/$clinicId'
    | '/api/public/clinics/$clinicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/categories'
    | '/compare'
    | '/dashboard'
    | '/promotions'
    | '/clinic/$clinicId'
    | '/api/public/bookings'
    | '/api/public/clinics'
    | '/api/public/clinic/$clinicId'
    | '/api/public/clinics/$clinicId'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/auth'
    | '/categories'
    | '/compare'
    | '/dashboard'
    | '/promotions'
    | '/clinic/$clinicId'
    | '/api/public/bookings'
    | '/api/public/clinics'
    | '/api/public/clinic/$clinicId'
    | '/api/public/clinics/$clinicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  PromotionsRoute: typeof PromotionsRoute
  ClinicClinicIdRoute: typeof ClinicClinicIdRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  ApiPublicClinicsRoute: typeof ApiPublicClinicsRouteWithChildren
  ApiPublicClinicClinicIdRoute: typeof ApiPublicClinicClinicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicId': {
      id: '/clinic/$clinicId'
      path: '/clinic/$clinicId'
      fullPath: '/clinic/$clinicId'
      preLoaderRoute: typeof ClinicClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clinics': {
      id: '/api/public/clinics'
      path: '/api/public/clinics'
      fullPath: '/api/public/clinics'
      preLoaderRoute: typeof ApiPublicClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clinics/$clinicId': {
      id: '/api/public/clinics/$clinicId'
      path: '/$clinicId'
      fullPath: '/api/public/clinics/$clinicId'
      preLoaderRoute: typeof ApiPublicClinicsClinicIdRouteImport
      parentRoute: typeof ApiPublicClinicsRoute
    }
    '/api/public/clinic/$clinicId': {
      id: '/api/public/clinic/$clinicId'
      path: '/api/public/clinic/$clinicId'
      fullPath: '/api/public/clinic/$clinicId'
      preLoaderRoute: typeof ApiPublicClinicClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicClinicsRouteChildren {
  ApiPublicClinicsClinicIdRoute: typeof ApiPublicClinicsClinicIdRoute
}

const ApiPublicClinicsRouteChildren: ApiPublicClinicsRouteChildren = {
  ApiPublicClinicsClinicIdRoute: ApiPublicClinicsClinicIdRoute,
}

const ApiPublicClinicsRouteWithChildren =
  ApiPublicClinicsRoute._addFileChildren(ApiPublicClinicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  PromotionsRoute: PromotionsRoute,
  ClinicClinicIdRoute: ClinicClinicIdRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  ApiPublicClinicsRoute: ApiPublicClinicsRouteWithChildren,
  ApiPublicClinicClinicIdRoute: ApiPublicClinicClinicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
